#!/bin/bash

OPTS="--enable=all --std=c99 --addon=scripts/cppcheck.json --suppressions-list=scripts/cppcheck.suppressions -Iinclude"

for filename in ./src/core/*.c; do
  cppcheck ${OPTS} ${filename}
done

for filename in ./src/hal/*.c; do
  cppcheck ${OPTS} ${filename}
done

for filename in ./examples/*.c; do
  cppcheck ${OPTS} ${filename}
done
