name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install unmanaged dependencies
        run: sudo apt-get install cmake gcc-avr binutils-avr avr-libc cmake cpputest

      - name: Build examples
        run: ./scripts/build

      - name: Run static analyzer
        run: echo "Static anlysis on github is temporarily disabled"

      - name: Run tests
        run: ./scripts/test





