name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install unmanaged dependencies
        run: sudo apt-get install cmake gcc-avr binutils-avr cmake

      - name: Build examples
        run: ./scripts/build





